SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS HUB_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE HUB_db;

CREATE TABLE `provinces`(
    `provinceID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL
);
CREATE TABLE `communes`(
    `communeID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `provinceID` BIGINT NOT NULL,
    `name` VARCHAR(100) NOT NULL
);
CREATE TABLE `services`(
    `serviceID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(100) NOT NULL,
    `realTitle` TEXT NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `url` TEXT NOT NULL,
    `buttonPosition` INT NOT NULL,
    `active` BOOLEAN NOT NULL
);
CREATE TABLE `service_documents`(
    `sdID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `serviceID` BIGINT NOT NULL,
    `realTitle` TEXT NOT NULL,
    `sourceType` ENUM('SCAN', 'FORM') NOT NULL DEFAULT 'SCAN',
    `formKey` CHAR(100) NULL,
    `sourceRef` CHAR(100) NULL,
    `active` BOOLEAN NOT NULL DEFAULT 1
);
CREATE TABLE `scan_requirements`(
    `srID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `serviceID` BIGINT NOT NULL,
    `code` CHAR(50) NOT NULL,
    `title` VARCHAR(100) NOT NULL,
    `description` TEXT NOT NULL,
    `required` BOOLEAN NOT NULL DEFAULT 0,
    `ocr_enabled` BOOLEAN NOT NULL DEFAULT 0
);
ALTER TABLE
    `communes` ADD CONSTRAINT `communes_provinceid_foreign` FOREIGN KEY(`provinceID`) REFERENCES `provinces`(`provinceID`) ON DELETE CASCADE;
ALTER TABLE
    `service_documents` ADD CONSTRAINT `service_documents_serviceid_foreign` FOREIGN KEY(`serviceID`) REFERENCES `services`(`serviceID`) ON DELETE CASCADE;
ALTER TABLE
    `scan_requirements` ADD CONSTRAINT `scan_requirements_serviceid_foreign` FOREIGN KEY(`serviceID`) REFERENCES `services`(`serviceID`) ON DELETE CASCADE;

-- INSERT INTO `provinces` (`provinceID`, `name`) VALUES 
-- (1, 'Thành phố Hà Nội'),
-- (2, 'Thành phố Hồ Chí Minh');

-- INSERT INTO `communes` (`provinceID`, `name`) VALUES 
-- (1, 'Phường Ba Đình'),
-- (1, 'Phường Ngọc Hà'),
-- (1, 'Phường Giảng Võ'),
-- (1, 'Phường Hoàn Kiếm'),
-- (1, 'Phường Cửa Nam'),
-- (1, 'Phường Phú Thượng'),
-- (1, 'Phường Hồng Hà'),
-- (1, 'Phường Tây Hồ'),
-- (1, 'Phường Bồ Đề'),
-- (1, 'Phường Việt Hưng'),
-- (1, 'Phường Phúc Lợi'),
-- (1, 'Phường Long Biên'),
-- (1, 'Phường Nghĩa Đô'),
-- (1, 'Phường Cầu Giấy'),
-- (1, 'Phường Yên Hòa'),
-- (1, 'Phường Ô Chợ Dừa'),
-- (1, 'Phường Láng'),
-- (1, 'Phường Văn Miếu - Quốc Tử Giám'),
-- (1, 'Phường Kim Liên'),
-- (1, 'Phường Đống Đa'),
-- (1, 'Phường Hai Bà Trưng'),
-- (1, 'Phường Vĩnh Tuy'),
-- (1, 'Phường Bạch Mai'),
-- (1, 'Phường Vĩnh Hưng'),
-- (1, 'Phường Định Công'),
-- (1, 'Phường Tương Mai'),
-- (1, 'Phường Lĩnh Nam'),
-- (1, 'Phường Hoàng Mai'),
-- (1, 'Phường Hoàng Liệt'),
-- (1, 'Phường Yên Sở'),
-- (1, 'Phường Phương Liệt'),
-- (1, 'Phường Khương Đình'),
-- (1, 'Phường Thanh Xuân'),
-- (1, 'Xã Sóc Sơn'),
-- (1, 'Xã Kim Anh'),
-- (1, 'Xã Trung Giã'),
-- (1, 'Xã Đa Phúc'),
-- (1, 'Xã Nội Bài'),
-- (1, 'Xã Đông Anh'),
-- (1, 'Xã Phúc Thịnh'),
-- (1, 'Xã Thư Lâm'),
-- (1, 'Xã Thiên Lộc'),
-- (1, 'Xã Vĩnh Thanh'),
-- (1, 'Xã Phù Đổng'),
-- (1, 'Xã Thuận An'),
-- (1, 'Xã Gia Lâm'),
-- (1, 'Xã Bát Tràng'),
-- (1, 'Phường Từ Liêm'),
-- (1, 'Phường Thượng Cát'),
-- (1, 'Phường Đông Ngạc'),
-- (1, 'Phường Xuân Đỉnh'),
-- (1, 'Phường Tây Tựu'),
-- (1, 'Phường Phú Diễn'),
-- (1, 'Phường Xuân Phương'),
-- (1, 'Phường Tây Mỗ'),
-- (1, 'Phường Đại Mỗ'),
-- (1, 'Xã Thanh Trì'),
-- (1, 'Phường Thanh Liệt'),
-- (1, 'Xã Đại Thanh'),
-- (1, 'Xã Ngọc Hồi'),
-- (1, 'Xã Nam Phù'),
-- (1, 'Xã Yên Xuân'),
-- (1, 'Xã Quang Minh'),
-- (1, 'Xã Yên Lãng'),
-- (1, 'Xã Tiến Thắng'),
-- (1, 'Xã Mê Linh'),
-- (1, 'Phường Kiến Hưng'),
-- (1, 'Phường Hà Đông'),
-- (1, 'Phường Yên Nghĩa'),
-- (1, 'Phường Phú Lương'),
-- (1, 'Phường Sơn Tây'),
-- (1, 'Phường Tùng Thiện'),
-- (1, 'Xã Đoài Phương'),
-- (1, 'Xã Quảng Oai'),
-- (1, 'Xã Cổ Đô'),
-- (1, 'Xã Minh Châu'),
-- (1, 'Xã Vật Lại'),
-- (1, 'Xã Bất Bạt'),
-- (1, 'Xã Suối Hai'),
-- (1, 'Xã Ba Vì'),
-- (1, 'Xã Yên Bài'),
-- (1, 'Xã Phúc Thọ'),
-- (1, 'Xã Phúc Lộc'),
-- (1, 'Xã Hát Môn'),
-- (1, 'Xã Đan Phượng'),
-- (1, 'Xã Liên Minh'),
-- (1, 'Xã Ô Diên'),
-- (1, 'Xã Hoài Đức'),
-- (1, 'Xã Dương Hòa'),
-- (1, 'Xã Sơn Đồng'),
-- (1, 'Xã An Khánh'),
-- (1, 'Phường Dương Nội'),
-- (1, 'Xã Quốc Oai'),
-- (1, 'Xã Kiều Phú'),
-- (1, 'Xã Hưng Đạo'),
-- (1, 'Xã Phú Cát'),
-- (1, 'Xã Thạch Thất'),
-- (1, 'Xã Hạ Bằng'),
-- (1, 'Xã Hòa Lạc'),
-- (1, 'Xã Tây Phương'),
-- (1, 'Phường Chương Mỹ'),
-- (1, 'Xã Phú Nghĩa'),
-- (1, 'Xã Xuân Mai'),
-- (1, 'Xã Quảng Bị'),
-- (1, 'Xã Trần Phú'),
-- (1, 'Xã Hòa Phú'),
-- (1, 'Xã Thanh Oai'),
-- (1, 'Xã Bình Minh'),
-- (1, 'Xã Tam Hưng'),
-- (1, 'Xã Dân Hòa'),
-- (1, 'Xã Thường Tín'),
-- (1, 'Xã Hồng Vân'),
-- (1, 'Xã Thượng Phúc'),
-- (1, 'Xã Chương Dương'),
-- (1, 'Xã Phú Xuyên'),
-- (1, 'Xã Phượng Dực'),
-- (1, 'Xã Chuyên Mỹ'),
-- (1, 'Xã Đại Xuyên'),
-- (1, 'Xã Vân Đình'),
-- (1, 'Xã Ứng Thiên'),
-- (1, 'Xã Ứng Hòa'),
-- (1, 'Xã Hòa Xá'),
-- (1, 'Xã Mỹ Đức'),
-- (1, 'Xã Phúc Sơn'),
-- (1, 'Xã Hồng Sơn'),
-- (1, 'Xã Hương Sơn');

-- INSERT INTO `communes` (`provinceID`, `name`) VALUES 
-- (2, 'Phường Thủ Dầu Một'),
-- (2, 'Phường Phú Lợi'),
-- (2, 'Phường Bình Dương'),
-- (2, 'Phường Phú An'),
-- (2, 'Phường Chánh Hiệp'),
-- (2, 'Xã Dầu Tiếng'),
-- (2, 'Xã Minh Thạnh'),
-- (2, 'Xã Long Hòa'),
-- (2, 'Xã Thanh An'),
-- (2, 'Phường Bến Cát'),
-- (2, 'Xã Trừ Văn Thố'),
-- (2, 'Xã Bàu Bàng'),
-- (2, 'Phường Chánh Phú Hòa'),
-- (2, 'Phường Long Nguyên'),
-- (2, 'Phường Tây Nam'),
-- (2, 'Phường Thới Hòa'),
-- (2, 'Phường Hòa Lợi'),
-- (2, 'Xã Phú Giáo'),
-- (2, 'Xã Phước Thành'),
-- (2, 'Xã An Long'),
-- (2, 'Xã Phước Hòa'),
-- (2, 'Phường Tân Uyên'),
-- (2, 'Phường Tân Khánh'),
-- (2, 'Xã Bắc Tân Uyên'),
-- (2, 'Xã Thường Tân'),
-- (2, 'Phường Vĩnh Tân'),
-- (2, 'Phường Bình Cơ'),
-- (2, 'Phường Tân Hiệp'),
-- (2, 'Phường Dĩ An'),
-- (2, 'Phường Tân Đông Hiệp'),
-- (2, 'Phường Đông Hòa'),
-- (2, 'Phường Lái Thiêu'),
-- (2, 'Phường Thuận Giao'),
-- (2, 'Phường An Phú'),
-- (2, 'Phường Thuận An'),
-- (2, 'Phường Bình Hòa'),
-- (2, 'Phường Vũng Tàu'),
-- (2, 'Phường Tam Thắng'),
-- (2, 'Phường  Rạch Dừa'),
-- (2, 'Phường Phước Thắng'),
-- (2, 'Xã Long Sơn'),
-- (2, 'Phường Bà Rịa'),
-- (2, 'Phường Long Hương'),
-- (2, 'Phường Tam Long'),
-- (2, 'Xã Ngãi Giao'),
-- (2, 'Xã Xuân Sơn'),
-- (2, 'Xã Bình Giã'),
-- (2, 'Xã Châu Đức'),
-- (2, 'Xã Kim Long'),
-- (2, 'Xã Nghĩa Thành'),
-- (2, 'Xã Hồ Tràm'),
-- (2, 'Xã Xuyên Mộc'),
-- (2, 'Xã Bàu Lâm'),
-- (2, 'Xã Hòa Hội'),
-- (2, 'Xã Hòa Hiệp'),
-- (2, 'Xã Bình Châu'),
-- (2, 'Xã Long Điền'),
-- (2, 'Xã Long Hải'),
-- (2, 'Xã Đất Đỏ'),
-- (2, 'Xã Phước Hải'),
-- (2, 'Phường Phú Mỹ'),
-- (2, 'Phường Tân Hải'),
-- (2, 'Phường Tân Phước'),
-- (2, 'Phường Tân Thành'),
-- (2, 'Xã Châu Pha'),
-- (2, 'Đặc khu Côn Đảo'),
-- (2, 'Phường Tân Định'),
-- (2, 'Phường Sài Gòn'),
-- (2, 'Phường Bến Thành'),
-- (2, 'Phường Cầu Ông Lãnh'),
-- (2, 'Phường An Phú Đông'),
-- (2, 'Phường Thới An'),
-- (2, 'Phường Tân Thới Hiệp'),
-- (2, 'Phường Trung Mỹ Tây'),
-- (2, 'Phường Đông Hưng Thuận'),
-- (2, 'Phường Linh Xuân'),
-- (2, 'Phường Tam Bình'),
-- (2, 'Phường Hiệp Bình'),
-- (2, 'Phường Thủ Đức'),
-- (2, 'Phường Long Bình'),
-- (2, 'Phường Tăng Nhơn Phú'),
-- (2, 'Phường Phước Long'),
-- (2, 'Phường Long Phước'),
-- (2, 'Phường Long Trường'),
-- (2, 'Phường  An Nhơn'),
-- (2, 'Phường An Hội Đông'),
-- (2, 'Phường An Hội Tây'),
-- (2, 'Phường Gò Vấp'),
-- (2, 'Phường Hạnh Thông'),
-- (2, 'Phường Thông Tây Hội'),
-- (2, 'Phường Bình Lợi Trung'),
-- (2, 'Phường Bình Quới'),
-- (2, 'Phường Bình Thạnh'),
-- (2, 'Phường Gia Định'),
-- (2, 'Phường Thạnh Mỹ Tây'),
-- (2, 'Phường Tân Sơn Nhất'),
-- (2, 'Phường Tân Sơn Hòa'),
-- (2, 'Phường Bảy Hiền'),
-- (2, 'Phường Tân Hòa'),
-- (2, 'Phường Tân Bình'),
-- (2, 'Phường Tân Sơn'),
-- (2, 'Phường Tây Thạnh'),
-- (2, 'Phường Tân Sơn Nhì'),
-- (2, 'Phường Phú Thọ Hòa'),
-- (2, 'Phường Phú Thạnh'),
-- (2, 'Phường Tân Phú'),
-- (2, 'Phường Đức Nhuận'),
-- (2, 'Phường Cầu Kiệu'),
-- (2, 'Phường Phú Nhuận'),
-- (2, 'Phường An Khánh'),
-- (2, 'Phường Bình Trưng'),
-- (2, 'Phường Cát Lái'),
-- (2, 'Phường Xuân Hòa'),
-- (2, 'Phường Nhiêu Lộc'),
-- (2, 'Phường Bàn Cờ'),
-- (2, 'Phường Hòa Hưng'),
-- (2, 'Phường Diên Hồng'),
-- (2, 'Phường Vườn Lài'),
-- (2, 'Phường Hòa Bình'),
-- (2, 'Phường Phú Thọ'),
-- (2, 'Phường Bình Thới'),
-- (2, 'Phường Minh Phụng'),
-- (2, 'Phường Xóm Chiếu'),
-- (2, 'Phường Khánh Hội'),
-- (2, 'Phường Vĩnh Hội'),
-- (2, 'Phường Chợ Quán'),
-- (2, 'Phường An Đông'),
-- (2, 'Phường Chợ Lớn'),
-- (2, 'Phường Phú Lâm'),
-- (2, 'Phường Bình Phú'),
-- (2, 'Phường Bình Tây'),
-- (2, 'Phường Bình Tiên'),
-- (2, 'Phường Chánh Hưng'),
-- (2, 'Phường Bình Đông'),
-- (2, 'Phường Phú Định'),
-- (2, 'Phường Bình Hưng Hòa'),
-- (2, 'Phường Bình Tân'),
-- (2, 'Phường Bình Trị Đông'),
-- (2, 'Phường Tân Tạo'),
-- (2, 'Phường An Lạc'),
-- (2, 'Phường Tân Hưng'),
-- (2, 'Phường Tân Thuận'),
-- (2, 'Phường Phú Thuận'),
-- (2, 'Phường Tân Mỹ'),
-- (2, 'Xã Tân An Hội'),
-- (2, 'Xã An Nhơn Tây'),
-- (2, 'Xã Nhuận Đức'),
-- (2, 'Xã Thái Mỹ'),
-- (2, 'Xã Phú Hòa Đông'),
-- (2, 'Xã Bình Mỹ'),
-- (2, 'Xã Củ Chi'),
-- (2, 'Xã Hóc Môn'),
-- (2, 'Xã Đông Thạnh'),
-- (2, 'Xã Xuân Thới Sơn'),
-- (2, 'Xã Bà Điểm'),
-- (2, 'Xã Tân Nhựt'),
-- (2, 'Xã Vĩnh Lộc'),
-- (2, 'Xã Tân Vĩnh Lộc'),
-- (2, 'Xã Bình Lợi'),
-- (2, 'Xã Bình Hưng'),
-- (2, 'Xã Hưng Long'),
-- (2, 'Xã Bình Chánh'),
-- (2, 'Xã Nhà Bè'),
-- (2, 'Xã Hiệp Phước'),
-- (2, 'Xã Cần Giờ'),
-- (2, 'Xã Bình Khánh'),
-- (2, 'Xã An Thới Đông'),
-- (2, 'Xã Thạnh An');